language: node_js
node_js:
- node
notifications:
  email: false
script:
- npm run test
before_deploy:
- npm run doc
- npm run build
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master
