language: node_js
node_js:
  - node
notifications:
  email: false
before_script:
  - npm run build-ts
script:
  - npm run test
before_deploy:
  - npm run build
  - cp wdist/sage-bundle.js dist/sage-bundle.js
deploy:
- provider: npm
  skip_cleanup: true
  email: tminier01@gmail.com
  api_key: $NPM_KEY
  on:
    tags: true
